# Generated by Django 5.0.6 on 2024-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('facing', models.CharField(max_length=10)),
                ('club_house', models.BooleanField(default=False)),
                ('play_area', models.BooleanField(default=False)),
                ('water_supply', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('nearby_hsptl_km', models.FloatField()),
                ('parking', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('bathrooms', models.FloatField()),
                ('size', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
